export const ipcKeys = {
  CONNECT: 'connect',
  DBINFO: 'dbinfo',
  REGIST_FAV: 'regist_fav',
  SEND_FAV: 'send_fav',
  SEND_DB: 'send-db',
  SEND_TABLE: 'send-table',
  SHOW_TABLES: 'show-table',
  SHOW_RECORDS: 'show-records',
  WIN_CLOSE: 'window-close',
  WIN_MAX: 'window-max',
  WIN_MIN: 'window-min',
  WIN_RESTORE: 'window-resore',
  TITLE: 'title',
};
